name: Deploy Nginx

on:
  push:
    branches:
    - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v2

    - name: Install kubectl
      run: |
        sudo apt-get update
        sudo apt-get install kubectl

    - name: Configure kubectl for GKE
      run: |
        gcloud container clusters get-credentials autopilot-cluster-1 --region us-central1
        sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" resources.yaml
        kubectl apply -f resources.yaml

      env:
        CLOUDSDK_METRICS_ENVIRONMENT: github-actions-setup-gcloud
        GCLOUD_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        GOOGLE_APPLICATION_CREDENTIALS: /home/runner/work/github-actions-gcp-demo/github-actions-gcp-demo/ad40b2e61a401e79961d7293
        GOOGLE_GHA_CREDS_PATH: /home/runner/work/github-actions-gcp-demo/github-actions-gcp-demo/ad40b2e61a401e79961d7293
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}

    - name: Build and push the Docker image to Docker Hub
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      run: |
        docker build -t $DOCKERHUB_USERNAME/nginx:latest .
        docker login -u $DOCKERHUB_USERNAME -p "${{ secrets.DOCKERHUB_PASSWORD }}"
        docker push $DOCKERHUB_USERNAME/nginx:latest
